### ISSUE TITLE
Problems when converting from XLIFF to TSV using the translation

### ISSUE THREAD

**Issue by LLCampos** [matecat/MateCat-Filters#4] opened 2016-08-10 11:16 UTC
Hi, 

When I try to convert a XLIFF (resulting from the conversion of a TSV) back to a TSV using the original2xliff endpoint I get a "It was not possible to obtain the derived file from [name-of-the-file]" error. I've already try with three different TSV files.

(I'm still using the 1.1.4 version, but from what I checked none of the changes would this affect behavior.)

Thanks. :)

**Comment by giusilvano** [comment] 2016-08-11 11:11
Can you send me one of these files so I can debug them?

**Comment by LLCampos** [comment] 2016-08-11 11:47
[simple_tsv.tsv.txt](https://github.com/matecat/MateCat-Filters/files/413083/simple_tsv.tsv.txt)

Here it is. (I changed the suffix so that GitHub would let me upload the file) :)

**Comment by giusilvano** [comment] 2016-08-29 15:13
The cause of the issue seems to be in the Okapi Framework. I'll ask to them if they are already aware of this.

**Comment by giusilvano** [comment] 2016-09-14 14:26
We worked together with the Okapi team and found an issue in the filters configuration.
We already pushed a fix in the dev branch. Please try it and let me know if you still experience the issue. 
Thanks!

**Closed by giusilvano** 2016-09-14 14:26 UTC

**Comment by LLCampos** [comment] 2016-09-14 16:50
Ok, everything is working alright. 

But unfortunately the functionality also changed. Before, when there were two columns in the CSV/TSV, the first column would contain the pieces of text that would go to the <source> elements and the second column the pieces of text that would go to the <target> elements. 

Now, every value has his own triad of <source>, <seg-source> and <target> in the XLIFF. Was this change made on purpose?

**Comment by giusilvano** [comment] 2016-09-16 09:13
If I have properly understood, you want to treat CSV/TSV as bilingual files, with one column with source text and another column with target text. Unfortunately this feature is not supported by our Filters, even if the underlying Okapi Table Filter can support this configuration. All the texts in CSV and TSV are considered translatable.
